### ISSUE TITLE
Debian 9 stretch

### ISSUE THREAD

**Issue by pilasguru** [CoffeeITWorks/ansible_burp2_client#2]
Debian 9 changes libraries and produce an error with burp (client) installed and maintained with this role:

```
# burp -a l
burp: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by burp)
burp: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by burp)
```
OpenSSL has been updated.

Debian 9 has a burp package into repository:

```
Package: burp
Version: 2.0.54-1
Priority: extra
Section: utils
Maintainer: Calogero Lo Leggio <kalos@nerdrug.org>
Installed-Size: 681 kB
Depends: libacl1 (>= 2.2.51-8), libc6 (>= 2.15), libncurses5 (>= 6), librsync1 (>= 0.9.6), libssl1.1 (>= 1.1.0), libtinfo5 (>= 6), zlib1g (>= 1:1.1.4), lsb-base (>= 3.0-6)
```

and ansible see the Debian 9 Stretch by this way:

```
        "ansible_distribution": "Debian",
        "ansible_distribution_major_version": "9",
        "ansible_distribution_release": "stretch",
        "ansible_distribution_version": "9.0",
```

**Comment by pablodav** [comment]
Please try with: 

```yaml
burp_version: 2.1.10
```

to see if it compiles in debian 9. 

Recommended to add only to `host_vars/yourdebian9` for now.

**Comment by pablodav** [comment]
this was a requirement to recompile burp after upgrade, was not a clean install. 

it was easily solved running: 

    ansible-playbook -i production burp-client.yml -l client -e "burp_force_reinstall=yes"

I will add this information to readme and close this issue, will not close now to not forget about it.

**Comment by pablodav** [comment]
It's on latest version on README now!
