### ISSUE TITLE
building burp client on Debian 10. make install places burp in /usr/sbin/ not burp_bin_path

### ISSUE THREAD

**Issue by planet-winter** [CoffeeITWorks/ansible_burp2_client#28]
The current configure line variable needs to include `sbindir` to point to burp_bin_path or change path in os dependent vars file.
In:
```
- name: Make install
  shell: cd {{ download_dir }}/{{ burpsrc }} && make install creates={{ burp_bin_path }}

```
with:
```
burp_usr_path: '/usr/local'
burp_bin_path: "{{ burp_usr_path }}/sbin/burp"
```

and without:
`burp_configure_line: "CFLAGS='-O2 -march=native -mtune=native -mfpmath=sse' sbindir={{ burp_bin_path }} ./configure "`

Please note I have left out some CFLAGS: `-floop-parallelize-all -ftree-parallelize-loops=4` as they both didn't run on my FreeBSD VM. Might be that I don't have the predefined 4 Cores.

**Comment by pablodav** [comment]
Thanks you!

As I understood, I have to add `sbindir={{ burp_bin_path }} ` in `burp_configure_line` to fix it in Debian10 right?

How do you think we should handle the difference between freebsd and linux `burp_configure_line`?

I imagine only 1 option now:

1) Add `burp_configure_line` in vars/... os_specific setup.
cons: Users still have option to change the var but only on precedence 16. or higher: 
https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
Pros: 
No additional changes required to the role required.
Only needs to be clarified in Readme in some "FreeBSD" section.

**Comment by planet-winter** [comment]
Hi Paplo

>I have to add sbindir={{ burp_bin_path }} in burp_configure_line to fix it in Debian10 right?

As is, the sbindir is set to `/usr/sbin/` most probably not only in Debian 10. This places the self compiled binaries there and they can not be found under `/usr/local/sbin` later as referenced by the `burp_bin_path` var.  It should point to the later, as according to the LSB, self compiled binaries would be placed under `/usr/local/sbin` anyway AFAIK.
So I would use the /usr/local/sbin for all Linux versions.

For the configure line I would use the following:

`burp_configure_line: "CFLAGS='-O2 -march=native -mtune=native -mfpmath=sse' sbindir={{ burp_bin_path }} -floop-parallelize-all -ftree-parallelize-loops={{ ansible_processor_vcpus }} ./configure "`

This would dynamically set the number of CPUs to compile with and works on my FreeBSD VM as well as it failed due to having less than 4 vcpus... Tested and pushed to my fork.

Sorry for not having been clearer and thank you for developing and caring for this role.
