### ISSUE TITLE
Centos 7 Support

### ISSUE THREAD

**Issue by mgrkisiek** [CoffeeITWorks/ansible_burp2_client#4]
Agent can't be install on Centos 7 . Many files need to be edited before to perform succesful install.

**Comment by pablodav** [comment]
Hello, 

Thanks for reporting!

I will check and perform fixes for it.

**Comment by pablodav** [comment]
I have just added a commit with required support in branch hotfix/4_centos7_suppport

It passed checks in my computer:

PLAY RECAP *********************************************************************
ansible_burp2_centos_7     : ok=29   changed=2    unreachable=0    failed=0
ansible_burp2_debian_8     : ok=27   changed=2    unreachable=0    failed=0
ansible_burp2_debian_9     : ok=25   changed=2    unreachable=0    failed=0
ansible_burp2_ubuntu_latest : ok=27   changed=2    unreachable=0    failed=0
ansible_burp2_ubuntu_trusty : ok=27   changed=0    unreachable=0    failed=0


could you see if it is valid? 

I will merge if everything is good tomorrow and create new version.
