### ISSUE TITLE
Add tweaks from timbrd

### ISSUE THREAD

**Issue by pablodav** [CoffeeITWorks/ansible_burp2_client#6]
@timbrd

I have noticed some tweaks with include/excludes in your fork that could be interesting to have in this role. 

Also some duplicated work as I have recently added centos7 and fedora support. 

Could you please sync your repo and check if you could create pull request with your changes?

**Comment by timbrd** [comment]
@pablodav I created a pull request with the missing tweaks

**Comment by pablodav** [comment]
Thanks you! @timbrd ,

Now it is in new version 1.3.1!
